spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:trade_mvp;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  data:
    redis:
      repositories:
        enabled: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 8080
app:
  redis:
    enabled: false
  mq:
    enabled: false
  order:
    timeout-seconds: 15
    cache-ttl-seconds: 120
    empty-ttl-seconds: 30
