spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:trade_mvp;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  flyway:
    enabled: false
  data:
    redis:
      repositories:
        enabled: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 8080
app:
  matching:
    enabled: false
  outbox:
    enabled: true
    poll-interval-ms: 1000
    retry-delay-ms: 30000
  redis:
    enabled: false
  mq:
    enabled: false
    customer-order-timeout-topic: customer-order-timeout-topic
  order:
    timeout-seconds: 15
    cache-ttl-seconds: 120
    empty-ttl-seconds: 30
  payment:
    timeout-seconds: 300
    mode: mock
    callback-secret: mock-signature
    callback-base-url: https://xwycx.xyz
    alipay-app-id: sandbox-local-app
    alipay-sandbox-gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    compensation-enabled: true
    compensation-retry-interval-ms: 60000
  sms:
    provider: local
    local-code: 123456
    code-length: 6
    code-ttl-seconds: 300
  wechat:
    app-id: local-app
    app-secret: ""
    code2-session-url: https://api.weixin.qq.com/sns/jscode2session
